const restaurants = [
  {
    name: 'Dodo Pizza Tallinn',
    image_url: '/restaurants/1.png',
    street: 'Gonsiori 10',
    description: "Enjoy our delicious pizza and great atmosphere!",
  },
  {
    name: 'Dodo Pizza Munich',
    image_url: '/restaurants/2.png',
    street: 'Rosenheimer Str. 30',
    description: "Relish our mouthwatering pizza and delightful surroundings!",
  },
];

const menu = [
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Pepperoni',
    topping: ["cheese", "salami"],
    rank: 5,
    price: 10,
    pizza_image_url: '/pizza/pepperoni.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Margherita',
    topping: ["cheese", "tomato"],
    rank: 1,
    price: 12,
    pizza_image_url: '/pizza/margherita.webp',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Supreme',
    topping: ["cheese", "pepperoni", "mushrooms", "bell peppers", "olives"],
    rank: 2,
    price: 15,
    pizza_image_url: '/pizza/supreme.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Hawaiian',
    topping: ["cheese", "ham", "pineapple"],
    rank: 3,
    price: 11,
    pizza_image_url: '/pizza/hawaiian.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Vegetarian',
    topping: ["cheese", "mushrooms", "bell peppers", "onions", "olives"],
    rank: 4,
    price: 13,
    pizza_image_url: '/pizza/vegeterian.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'BBQ Chicken',
    topping: ["cheese", "BBQ chicken", "onions", "bell peppers"],
    rank: 6,
    price: 14,
    pizza_image_url: '/pizza/bbq-chicken.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Meat Lovers',
    topping: ["cheese", "sausage", "bacon", "pepperoni", "ham"],
    rank: 7,
    price: 16,
    pizza_image_url: '/pizza/meat-lovers.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Veggie Deluxe',
    topping: ["cheese", "mushrooms", "bell peppers", "olives", "onions", "tomato"],
    rank: 8,
    price: 14,
    pizza_image_url: '/pizza/veggie-deluxe.png',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Margarita',
    topping: ["cheese", "tomato", "basil"],
    rank: 9,
    price: 12,
    pizza_image_url: '/pizza/margarita.webp',
  },
  {
    category: 'pizza',
    restaurantId: 1,
    name: 'Seafood Supreme',
    topping: ["cheese", "shrimp", "calamari", "clams", "mussels"],
    rank: 10,
    price: 18,
    pizza_image_url: '/pizza/seafood-supreme.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Vegetarian',
    topping: ["cheese", "mushrooms", "bell peppers", "onions", "olives"],
    rank: 4,
    price: 13,
    pizza_image_url: '/pizza/vegeterian.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Pepperoni',
    topping: ["cheese", "salami"],
    rank: 3,
    price: 10,
    pizza_image_url: '/pizza/pepperoni.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Margherita',
    topping: ["cheese", "tomato"],
    rank: 6,
    price: 12,
    pizza_image_url: '/pizza/margherita.webp',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Supreme',
    topping: ["cheese", "pepperoni", "mushrooms", "bell peppers", "olives"],
    rank: 1,
    price: 15,
    pizza_image_url: '/pizza/supreme.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Hawaiian',
    topping: ["cheese", "ham", "pineapple"],
    rank: 7,
    price: 11,
    pizza_image_url: '/pizza/hawaiian.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'BBQ Chicken',
    topping: ["cheese", "BBQ chicken", "onions", "bell peppers"],
    rank: 2,
    price: 14,
    pizza_image_url: '/pizza/bbq-chicken.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Meat Lovers',
    topping: ["cheese", "sausage", "bacon", "pepperoni", "ham"],
    rank: 5,
    price: 16,
    pizza_image_url: '/pizza/meat-lovers.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Veggie Deluxe',
    topping: ["cheese", "mushrooms", "bell peppers", "olives", "onions", "tomato"],
    rank: 8,
    price: 14,
    pizza_image_url: '/pizza/veggie-deluxe.png',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Margarita',
    topping: ["cheese", "tomato", "basil"],
    rank: 9,
    price: 12,
    pizza_image_url: '/pizza/margarita.webp',
  },
  {
    category: 'pizza',
    restaurantId: 2,
    name: 'Seafood Supreme',
    topping: ["cheese", "shrimp", "calamari", "clams", "mussels"],
    rank: 10,
    price: 18,
    pizza_image_url: '/pizza/seafood-supreme.png',
  },
];

module.exports = {
  restaurants,
  menu,
};